const projects = [
    {
      id: "pasion-dance",
      title: "Pasion Dance",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1658290142/portfolio/pasion-dance_hp7nzs.jpg",
      alt: "Project 1",
      description: {
        es: "Sitio web para una academia de danzas orientales con identidad visual marcada y diseño responsivo.",
        en: "Website for an oriental dance academy with a strong visual identity and responsive layout.",
      },
      repo: "https://github.com/GeorgeValle/pasion-dance",
      demo: "http://rb.gy/cw1oin",
      youtube: null,
      featured: false,
      category: "web",
      tech: ["html", "css", "javascript", "responsive", "git", "github"],
    },
    {
      id: "staff-selection",
      title: "Staff Selection",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1658290134/portfolio/staff-selection_yuuwb8.jpg",
      alt: "Project 2",
      description: {
        es: "Prototipo de plataforma de empleo enfocado en visibilidad, usabilidad y estructura tipo dashboard.",
        en: "Employment platform prototype focused on visibility, usability and a dashboard-style structure.",
      },
      repo: "https://github.com/GeorgeValle/staff-selection",
      demo: "https://rb.gy/3kdviq",
      youtube: null,
      featured: false,
      category: "web",
      tech: ["html", "css", "javascript", "git", "github", "dashboard"],
    },
    {
      id: "my-freaky-shop",
      title: "My Freaky Shop",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1658290135/portfolio/my-freaky-shop_g7hqkt.jpg",
      alt: "Project 3",
      description: {
        es: "Proyecto estilo e-commerce con exploración de productos y una propuesta visual temática.",
        en: "E-commerce style project with product browsing and a strong themed visual approach.",
      },
      repo: "https://github.com/GeorgeValle/my-freaky-shop",
      demo: "https://rb.gy/izk1jc",
      youtube: null,
      featured: false,
      category: "web",
      tech: ["react", "javascript", "css", "responsive", "git", "github"],
    },
    {
      id: "wiki-ideas",
      title: "Wiki Ideas",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1690690417/portfolio/wiki-ideas_nc07n6.jpg",
      alt: "Project 4",
      description: {
        es: "Proyecto frontend para organización de ideas y visualización de contenido con una interfaz limpia.",
        en: "Frontend project for idea organization and content visualization with a clean interface.",
      },
      repo: "https://github.com/GeorgeValle/wiki_ideas_front",
      demo: "https://rb.gy/55pre",
      youtube: null,
      featured: true,
      category: "web",
      tech: ["react", "javascript", "css", "responsive", "git", "github"],
    },
    {
      id: "azure-store",
      title: "Azure Store",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1690771772/portfolio/azure-store_bcifhj.jpg",
      alt: "Project 5",
      description: {
        es: "Interfaz de tienda online con foco en experiencia de usuario, catálogo visual y estructura tipo dashboard.",
        en: "Online store interface focused on user experience, visual catalog and a dashboard-style structure.",
      },
      repo: "https://github.com/GeorgeValle/azur-store",
      demo: "https://rb.gy/hqtf7",
      youtube: null,
      featured: true,
      category: "web",
      tech: [
        "react",
        "javascript",
        "css",
        "responsive",
        "git",
        "github",
        "dashboard",
      ],
    },
    {
      id: "invitation-birthday",
      title: "Invitation Birthday",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1693689463/portfolio/invitation-brithday_lvhjwx.jpg",
      alt: "Project 6",
      description: {
        es: "Landing page interactiva para invitación de cumpleaños con una estética visual personalizada.",
        en: "Interactive birthday invitation landing page with a custom visual style.",
      },
      repo: "https://github.com/GeorgeValle/birthday-invitation",
      demo: "https://rb.gy/iacrz",
      youtube: null,
      featured: false,
      category: "web",
      tech: ["html", "css", "javascript", "responsive", "git", "github"],
    },
    {
      id: "face-race",
      title: "Face Race",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1751514617/portfolio/colaneri_e_hijos_h5dr19.png",
      alt: "Project 7",
      description: {
        es: "Sistema de gestión orientado a negocio real, con interfaz tipo dashboard desarrollada para la empresa Colaneri.",
        en: "Business management system with a dashboard-style interface built for the company Colaneri.",
      },
      repo: "https://github.com/GeorgeValle/face-race-front",
      demo: "https://colaneriehijos.netlify.app/",
      youtube: "https://youtu.be/1dOzcBNHlaY",
      featured: true,
      category: "web",
      tech: ["react", "javascript", "css", "git", "github", "dashboard"],
    },
    {
      id: "meteo-clima",
      title: "Meteo Clima",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1776565230/portfolio/Captura_de_pantalla_2026-04-18_231626_o54v3e.png",
      alt: "Project 8",
      description: {
        es: "Aplicación del clima enfocada en interfaz responsiva, manejo limpio de estados y consumo de APIs externas.",
        en: "Weather application focused on responsive interface, clean state handling and external API consumption.",
      },
      repo: "https://github.com/GeorgeValle/meteo-clima",
      demo: "https://georgevalle.github.io/meteo-clima/",
      youtube: null,
      featured: true,
      category: "web",
      tech: [
        "angular",
        "typescript",
        "css",
        "api",
        "responsive",
        "git",
        "github",
        "sdd",
      ],
    },
    {
      id: "organizador-tareas",
      title: "Organizador de tareas",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1776572943/portfolio/organizador-tareas_i0pqnq.png",
      alt: "Project 9",
      description: {
        es: "Aplicación para organizar tareas con una interfaz práctica, clara y construida con Angular y TypeScript.",
        en: "Task organization app with a practical and clear interface built with Angular and TypeScript.",
      },
      repo: "https://github.com/GeorgeValle/organizador-tareas",
      demo: "https://georgevalle.github.io/organizador-tareas/",
      youtube: null,
      featured: false,
      category: "web",
      tech: [
        "angular",
        "typescript",
        "css",
        "git",
        "github",
        "responsive",
        "sdd",
      ],
    },
    {
      id: "aquatic-minesweeper",
      title: "Aquatic Minesweeper",
      image:
        "https://res.cloudinary.com/georgevalle/image/upload/v1776576566/portfolio/minesweeper_kajwlv.png",
      alt: "Project 10",
      description: {
        es: "Versión temática de Buscaminas con lógica interactiva en React y una propuesta visual inspirada en el mundo acuático.",
        en: "Themed Minesweeper version built with React, featuring interactive game logic and visuals inspired by the aquatic world.",
      },
      repo: "https://github.com/GeorgeValle/minesweeper",
      demo: "https://georgevalle.github.io/minesweeper/",
      youtube: null,
      featured: false,
      category: "game",
      tech: ["react", "css", "javascript", "git", "github", "game", "sdd"],
    },
  ];
  
  export default projects;